# Generated by Django 5.1.6 on 2026-02-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_email_verified_profile_failed_login_attempts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_verification_otp_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_verification_otp_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_verification_otp_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
