# Generated by Django 5.1.6 on 2026-02-20 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('was_accepted', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('receipt', 'Receipt')], default='manual', max_length=20)),
                ('model_version', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corrected_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_corrected', to='finance.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_feedback_entries', to=settings.AUTH_USER_MODEL)),
                ('predicted_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_predicted', to='finance.category')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_feedback_entries', to='finance.transaction')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CategoryModelState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_data', models.JSONField(blank=True, default=dict)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('feedback_count_since_train', models.PositiveIntegerField(default=0)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category_model_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ReceiptIngestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('raw_text', models.TextField(blank=True)),
                ('merchant', models.CharField(blank=True, max_length=160)),
                ('detected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('detected_date', models.DateField(blank=True, null=True)),
                ('txn_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='expense', max_length=10)),
                ('category_confidence', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('parsed', 'Parsed'), ('imported', 'Imported'), ('failed', 'Failed')], default='parsed', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_receipts', to='finance.transaction')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_ingestions', to=settings.AUTH_USER_MODEL)),
                ('suggested_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_suggestions', to='finance.category')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
