# Generated by Django 5.1.6 on 2026-02-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transaction_recurrence_for_date_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('sbi', 'SBI Bank'), ('hdfc', 'HDFC Bank'), ('icici', 'ICICI Bank'), ('axis', 'Axis Bank'), ('kotak', 'Kotak Bank'), ('pnb', 'Punjab National Bank'), ('bob', 'Bank of Baroda'), ('canara', 'Canara Bank'), ('wallet', 'Wallet'), ('credit', 'Credit Card')], default='bank', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
