# Generated by Django 5.1.6 on 2026-02-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_account_account_type_alter_account_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('wallet', 'Wallet'), ('credit', 'Credit Card'), ('other', 'Other')], default='bank', max_length=20),
        ),
    ]
